import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import  JotaiProvider  from "@/providers/JotaiProvider";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex h-screen bg-gray-50 dark:bg-slate-900`}
      >
        <AuthProvider>
          <JotaiProvider>
          <ThemeProvider>
            <Sidebar />
            <main className="flex-1 overflow-auto p-6 ml-64">{children}</main>
          </ThemeProvider>
          </JotaiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
