'use client';
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import JotaiProvider from "@/providers/JotaiProvider";
import { AuthProvider } from "@/context/AuthContext";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const publicRoutes = ["/", "/register"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isPublicRoute = publicRoutes.includes(pathname || '');

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} h-screen bg-gray-50 dark:bg-slate-900 ${isPublicRoute ? 'flex items-center justify-center' : 'flex'}`}
      >
        <AuthProvider>
          <JotaiProvider>
            <ThemeProvider>
              {/* <Sidebar /> */}
              {!isPublicRoute && <Sidebar />}
              <main
                className={`${isPublicRoute ? 'w-full max-w-4xl' : 'flex-1 overflow-auto p-6 lg:ml-64'}`}
              >
                {children}
              </main>
            </ThemeProvider>
          </JotaiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
